// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKl_8GXKLvGEt0IQubcJ7i2Mf54DEtn1k',
    appId: '1:900386620580:android:dea0e63509d287d32b5231',
    messagingSenderId: '900386620580',
    projectId: 'smart-home-82ebb',
    databaseURL: 'https://smart-home-82ebb-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-82ebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIS4Et8dxFnqVsXMr0ilUQFpbVY5D0VVE',
    appId: '1:900386620580:ios:a6f2d4ec035ef9e22b5231',
    messagingSenderId: '900386620580',
    projectId: 'smart-home-82ebb',
    databaseURL: 'https://smart-home-82ebb-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-82ebb.firebasestorage.app',
    iosBundleId: 'com.example.smartHome',
  );

}